# Generated by Django 4.2.30 on 2026-04-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
    ]
