# Generated by Django 4.2.30 on 2026-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('DIRECT', 'Direct (1:1)'), ('GROUP', 'Group')], default='DIRECT', max_length=16),
        ),
    ]
